version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: healthcare-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
      MYSQL_USER: user
      MYSQL_PASSWORD: healthcare1234
      TZ: Asia/Seoul
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge