version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: healthcare-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare
      MYSQL_USER: user
      MYSQL_PASSWORD: healthcare1234
      TZ: Asia/Seoul
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.2.5
    container_name: healthcare-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge