spring.application.name: link

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/healthcare?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: healthcare1234
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 3s
      database: 0
      lettuce:
        pool:
          max-wait: 3s

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /api/**
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha